job_specifications:
- id: namdjob
  auto_complete: true
  shm_size: 256m
  tasks:
  - docker_image: alfpark/namd:2.11-icc-mkl-intelmpi
    resource_files:
    - blob_source: https://raw.githubusercontent.com/Azure/batch-shipyard/master/recipes/NAMD-Infiniband-IntelMPI/docker/set_up_namd.sh
      file_path: set_up_namd.sh
    multi_instance:
      num_instances: pool_current_dedicated
      pre_execution_command: source set_up_namd.sh apoa1 1000
      mpi:
        runtime: intelmpi
        processes_per_node: 16
    command: $NAMD_DIR/namd2 apoa1.namd
