version: "3.5"

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  backend:
    driver: bridge

services:
  heimdall:
    image: alfpark/batch-shipyard:{BATCH_SHIPYARD_VERSION}-heimdall
    container_name: heimdall
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - /var/batch-shipyard/prometheus:/var/batch-shipyard/prometheus
      - /var/batch-shipyard/heimdall.json:/etc/heimdall.json
    command:
      - --conf
      - /etc/heimdall.json

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      {PROMETHEUS_PORT}
    networks:
      - backend
    links:
      - grafana
      - prometheus
    volumes:
      - /var/batch-shipyard/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/batch-shipyard/letsencrypt/html:/usr/share/nginx/html
      - /var/batch-shipyard/nginx/dhparam/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /var/batch-shipyard/letsencrypt/etc/{LE_CERT_DIR}:/etc/letsencrypt/live

  prometheus:
    image: prom/prometheus:v2.2.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090"
    volumes:
      - prometheus-storage:/prometheus
      - /var/batch-shipyard/prometheus:/conf
    networks:
      - backend
    command:
      - "--config.file=/conf/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention=1000h"
      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana:5.1.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - backend
    links:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - /var/batch-shipyard/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER={GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD={GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      {GF_SERVER_DOMAIN}
