pool_specification:
  id: cntk-cpu-multinode
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
  vm_count:
    dedicated: 3
    low_priority: 0
  vm_size: STANDARD_D1_V2
  inter_node_communication_enabled: true
  ssh:
    username: shipyard
