credentials:
  batch:
    aad:
      endpoint: https://batch.core.windows.net/
      directory_id: <AAD directory id>
      application_id: <AAD application id, if using SP login>
      auth_key: <Auth key for SP login>
      rsa_private_key_pem: <RSA private key for SP login>
      x509_cert_sha1_thumbprint: <X509 cert thumbprint for SP login>
      user: <AAD username for directory if using user login>
      password: <AAD password for username above if using user login without multi-factor auth>
      token_cache:
        enabled: true
        filename: .aad_token_cache
    account_service_url: https://<myaccount>.<region>.batch.azure.com
    resource_group: my-resource-group
  management:
    aad:
      endpoint: https://management.core.windows.net/
      directory_id: <AAD directory id>
      application_id: <AAD application id, if using SP login>
      auth_key: <Auth key for SP login>
      rsa_private_key_pem: <RSA private key for SP login>
      x509_cert_sha1_thumbprint: <X509 cert thumbprint for SP login>
      user: <AAD username for directory if using user login>
      password: <AAD password for username above if using user login without multi-factor auth>
      token_cache:
        enabled: true
        filename: .aad_token_cache
    subscription_id: <subscription id>
  storage:
    mystorageaccount:
      account: <storage account name>
      account_key: <storage account key>
      endpoint: core.windows.net
