batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - alfpark/mxnet:gpu
  docker_volumes:
    shared_data_volumes:
      glustervol:
        container_path: $AZ_BATCH_NODE_SHARED_DIR/gfs
        volume_driver: glusterfs_on_compute
